// <auto-generated />
using System;
using AutoInsight.Data;
using AutoInsight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace aspnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_role", new[] { "admin", "member" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invite_status", new[] { "pending", "accepted", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vehicle_model", new[] { "mottu_sport110i", "mottue", "honda_pop110i", "tvs_sport110i" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vehicle_status", new[] { "scheduled", "waiting", "on_service", "finished", "cancelled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoInsight.Models.Beacon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("major");

                    b.Property<string>("Minor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minor");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_beacons");

                    b.HasIndex("UUID")
                        .IsUnique()
                        .HasDatabaseName("ix_beacons_uuid");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_beacons_vehicle_id");

                    b.HasIndex("Major", "Minor")
                        .IsUnique()
                        .HasDatabaseName("ix_beacons_major_minor");

                    b.ToTable("beacons", (string)null);
                });

            modelBuilder.Entity("AutoInsight.Models.EmployeeInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InviterId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("inviter_id");

                    b.Property<EmployeeRole>("Role")
                        .HasColumnType("employee_role")
                        .HasColumnName("role");

                    b.Property<InviteStatus>("Status")
                        .HasColumnType("invite_status")
                        .HasColumnName("status");

                    b.Property<Guid>("YardId")
                        .HasColumnType("uuid")
                        .HasColumnName("yard_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_invites");

                    b.HasIndex("YardId")
                        .HasDatabaseName("ix_employee_invites_yard_id");

                    b.ToTable("employee_invites", (string)null);
                });

            modelBuilder.Entity("AutoInsight.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<VehicleModel>("Model")
                        .HasColumnType("vehicle_model")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plate");

                    b.Property<VehicleStatus>("Status")
                        .HasColumnType("vehicle_status")
                        .HasColumnName("status");

                    b.Property<Guid>("YardId")
                        .HasColumnType("uuid")
                        .HasColumnName("yard_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_vehicles_assignee_id");

                    b.HasIndex("YardId")
                        .HasDatabaseName("ix_vehicles_yard_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("AutoInsight.Models.Yard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_yards");

                    b.ToTable("yards", (string)null);
                });

            modelBuilder.Entity("AutoInsight.Models.YardCapacitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("VehiclesInYard")
                        .HasColumnType("integer")
                        .HasColumnName("vehicles_in_yard");

                    b.Property<Guid>("YardId")
                        .HasColumnType("uuid")
                        .HasColumnName("yard_id");

                    b.HasKey("Id")
                        .HasName("pk_yard_capacity_snapshots");

                    b.HasIndex("YardId")
                        .HasDatabaseName("ix_yard_capacity_snapshots_yard_id");

                    b.ToTable("yard_capacity_snapshots", (string)null);
                });

            modelBuilder.Entity("AutoInsight.Models.YardEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<EmployeeRole>("Role")
                        .HasColumnType("employee_role")
                        .HasColumnName("role");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("YardId")
                        .HasColumnType("uuid")
                        .HasColumnName("yard_id");

                    b.HasKey("Id")
                        .HasName("pk_yard_employees");

                    b.HasIndex("YardId")
                        .HasDatabaseName("ix_yard_employees_yard_id");

                    b.ToTable("yard_employees", (string)null);
                });

            modelBuilder.Entity("AutoInsight.Models.Beacon", b =>
                {
                    b.HasOne("AutoInsight.Models.Vehicle", "Vehicle")
                        .WithOne("Beacon")
                        .HasForeignKey("AutoInsight.Models.Beacon", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beacons_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoInsight.Models.EmployeeInvite", b =>
                {
                    b.HasOne("AutoInsight.Models.Yard", "Yard")
                        .WithMany("Invites")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_invites_yards_yard_id");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("AutoInsight.Models.Vehicle", b =>
                {
                    b.HasOne("AutoInsight.Models.YardEmployee", "Assignee")
                        .WithMany("Vehicles")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vehicles_yard_employees_assignee_id");

                    b.HasOne("AutoInsight.Models.Yard", "Yard")
                        .WithMany("Vehicles")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_yards_yard_id");

                    b.Navigation("Assignee");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("AutoInsight.Models.YardCapacitySnapshot", b =>
                {
                    b.HasOne("AutoInsight.Models.Yard", "Yard")
                        .WithMany("CapacitySnapshots")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_yard_capacity_snapshots_yards_yard_id");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("AutoInsight.Models.YardEmployee", b =>
                {
                    b.HasOne("AutoInsight.Models.Yard", "Yard")
                        .WithMany("Employees")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_yard_employees_yards_yard_id");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("AutoInsight.Models.Vehicle", b =>
                {
                    b.Navigation("Beacon")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoInsight.Models.Yard", b =>
                {
                    b.Navigation("CapacitySnapshots");

                    b.Navigation("Employees");

                    b.Navigation("Invites");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoInsight.Models.YardEmployee", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
